color: null
fieldLayouts:
  6f9e3a5c-0956-4c48-9880-9d67d7326040:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:16:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d6b05608-00b5-43d3-a501-a9a872c36298
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:18:44+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subText
            includeInCards: false
            instructions: null
            label: 'Sub Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c3114b0-74ad-4197-b229-447083c9d2ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 305e5fe9-019e-42d7-b85a-98b96e73cac4
        userCondition: null
handle: locations
hasTitleField: true
icon: ''
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
