defaultPlacement: end
enableVersioning: true
entryTypes:
  - 26a13ec2-9d85-4303-8024-1dca989c1e22 # Categories
handle: categories
maxAuthors: 1
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry.twig
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: 64b6f371-e07a-4002-89b5-6d91749dca1e
type: structure
