defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4d931b38-7f50-45a8-a014-4da6922191d7 # Locations
handle: locations
maxAuthors: 1
name: Locations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry.twig
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: null
  uid: 631262da-fa89-483a-b1be-e62e5c2a783c
type: structure
