defaultPlacement: end
enableVersioning: true
entryTypes:
  - 87b337ed-84b8-4b42-b395-f49df9ef1cef # Navigation
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: cfa4c7d8-b31c-481b-bf6e-f2e756f8b7db
type: structure
